services:
  marketplace-db:
    image: postgres:16
    container_name: marketplace-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace
      TZ: Europe/Kyiv
    volumes:
      - marketplace_db:/var/lib/postgresql/data

  keycloak-db:
    image: postgres:16
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: keycloakdb
      POSTGRES_PASSWORD: keycloakdb
    volumes:
      - keycloak_db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloakdb -d keycloakdb" ]
      interval: 5s
      retries: 5
      timeout: 5s

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.1
    container_name: keycloak
    command: start-dev
    ports:
      - "8180:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloakdb
      KC_DB_USERNAME: keycloakdb
      KC_DB_PASSWORD: keycloakdb
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    depends_on:
      keycloak-db:
        condition: service_healthy

volumes:
  marketplace_db:
  keycloak_db:
